site_name: Team Diamonds

nav:
  - Home: README.md
  - Design: DESIGN.md
  - Contributing: CONTRIBUTING.md
  - Components:
    - Interface: INTERFACE.md
    - Jira Implementation: IMPLEMENTATION_JIRA.md
    - Jira Service: JIRA_SERVICE.md
    - Jira Service API Client: JIRA_SERVICE_API_CLIENT.md
    - Jira Service Adapter: JIRA_SERVICE_ADAPTER.md
